// <auto-generated />
using System;
using FMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FMS.API.Model.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "papaya-001",
                            Code = "001",
                            CreateDate = new DateTime(2026, 1, 27, 6, 7, 16, 821, DateTimeKind.Local).AddTicks(5009),
                            Name = "Papaya Green Queen"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "papaya-shani-002",
                            Code = "002",
                            CreateDate = new DateTime(2026, 1, 27, 6, 7, 16, 821, DateTimeKind.Local).AddTicks(5028),
                            Name = "Papaya Shahi"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "papaya-babu-003",
                            Code = "003",
                            CreateDate = new DateTime(2026, 1, 27, 6, 7, 16, 821, DateTimeKind.Local).AddTicks(5031),
                            Name = "Papaya Babu"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "papaya-004",
                            Code = "004",
                            CreateDate = new DateTime(2026, 1, 27, 6, 7, 16, 821, DateTimeKind.Local).AddTicks(5032),
                            Name = "Papaya Top Lady"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
